# Generated by Django 4.0.2 on 2022-04-18 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_colour_1', models.CharField(max_length=7)),
                ('team_colour_2', models.CharField(max_length=7)),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('website_url', models.URLField()),
                ('contact_number', models.CharField(max_length=10)),
                ('club_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('sport_clubs', models.ManyToManyField(related_name='sport_clubs', to='users.Club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='admin',
            field=models.ManyToManyField(related_name='club_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='member',
            field=models.ManyToManyField(related_name='club_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_sport', to='users.sport'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_club', to='users.club'),
        ),
    ]
